CREATE OR REPLACE EDITIONABLE TRIGGER bi_kommentar 
BEFORE INSERT ON KOMMENTAR 
FOR EACH ROW
BEGIN
    IF :NEW.KOMMENTAR_ID IS NULL THEN
        SELECT kommentar_seq.NEXTVAL
        INTO :NEW.KOMMENTAR_ID
        FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER bi_kommentar ENABLE;