CREATE OR REPLACE EDITIONABLE TRIGGER bi_mitarbeiter_seite_sperre 
BEFORE INSERT ON MITARBEITER_SEITE_SPERRE 
FOR EACH ROW
BEGIN
    IF :NEW.MITARBEITER_SEITE_SPERRE_ID IS NULL THEN
        SELECT MITARBEITER_SEITE_SPERRE_SEQ.NEXTVAL
        INTO :NEW.MITARBEITER_SEITE_SPERRE_ID
        FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER bi_mitarbeiter_seite_sperre ENABLE;