prompt --application/pages/page_00051
begin
--   Manifest
--     PAGE: 00051
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2023.04.28'
,p_release=>'23.1.0'
,p_default_workspace_id=>97227846552725811
,p_default_application_id=>102
,p_default_id_offset=>134035714542293292
,p_default_owner=>'SCHICHTPLANUNG'
);
wwv_flow_imp_page.create_page(
 p_id=>51
,p_name=>'Legende Vorgabe Codes'
,p_alias=>'LEGENDE-VORGABE-CODES'
,p_page_mode=>'MODAL'
,p_step_title=>'Legende Vorgabe Codes'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*// Code zur Initialisierung des Dialogs',
'function initDialog() {',
unistr('  // Code zur Initialisierung des Dialogs hier einf\00FCgen'),
'}',
'',
unistr('// Code zum \00D6ffnen des Dialogs'),
'function openDialog() {',
'  apex.navigation.dialog(''dialog_page_url'', {',
'    title: ''Dialogtitel'',',
'    height: ''600'',',
'    width: ''700'',',
'    maxWidth: ''200'',',
'    modal: true,',
'    dialog: null',
'  });',
'}',
'',
unistr('// Code zum Schlie\00DFen des Dialogs'),
'function closeDialog() {',
'  apex.navigation.dialog.close(true);',
'}',
'',
'// Code zum Abbrechen des Dialogs',
'function cancelDialog() {',
'  apex.navigation.dialog.close(false);',
'}',
'',
'// Code zum Binden der Funktionen an Ereignisse',
'$(document).ready(function() {',
'  apex.jQuery("#cr_sp_matrix").on("dialogopen", initDialog);',
'});',
'*/'))
,p_step_template=>wwv_flow_imp.id(98903941265580497)
,p_page_template_options=>'#DEFAULT#'
,p_dialog_height=>'900'
,p_dialog_width=>'700'
,p_dialog_max_width=>'900'
,p_protection_level=>'C'
,p_page_component_map=>'21'
,p_last_updated_by=>'SEM'
,p_last_upd_yyyymmddhh24miss=>'20230901150148'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(169527506211812751)
,p_plug_name=>'Button Container'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(98882280679580484)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_03'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(169527842102812754)
,p_plug_name=>'Vorgeabe Codes Legende'
,p_region_name=>'kommentar_ig'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_imp.id(98884152106580485)
,p_plug_display_sequence=>10
,p_query_type=>'TABLE'
,p_query_table=>'VORGABE_CODES'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IG'
,p_prn_units=>'MILLIMETERS'
,p_prn_paper_size=>'A4'
,p_prn_width=>297
,p_prn_height=>210
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'Monat Status Current'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115751075877113760)
,p_name=>'BEZEICHNUNG_KUERZEL'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BEZEICHNUNG_KUERZEL'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Vorgabe Code'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>30
,p_value_alignment=>'LEFT'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_max_length=>50
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750981837113759)
,p_name=>'DAUER_H'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'DAUER_H'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Std.'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>40
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750797280113757)
,p_name=>'BESCHREIBUNG'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'BESCHREIBUNG'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXTAREA'
,p_heading=>'Beschreibung'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>60
,p_value_alignment=>'LEFT'
,p_attribute_01=>'Y'
,p_attribute_02=>'N'
,p_attribute_03=>'N'
,p_attribute_04=>'BOTH'
,p_is_required=>false
,p_max_length=>250
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750607554113756)
,p_name=>'KUERZEL_PLANUNG'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'KUERZEL_PLANUNG'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Kuerzel Planung'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>70
,p_value_alignment=>'LEFT'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_max_length=>50
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750542292113755)
,p_name=>'STARTZEIT_H'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'STARTZEIT_H'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Start'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>80
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750455241113754)
,p_name=>'ENDZEIT_H'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ENDZEIT_H'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Ende'
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>90
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750398886113753)
,p_name=>'SERVICE_TEAM_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'SERVICE_TEAM_ID'
,p_data_type=>'NUMBER'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_NUMBER_FIELD'
,p_heading=>'Service Team '
,p_heading_alignment=>'RIGHT'
,p_display_sequence=>100
,p_value_alignment=>'RIGHT'
,p_attribute_03=>'right'
,p_attribute_04=>'text'
,p_is_required=>false
,p_enable_filter=>true
,p_filter_is_required=>false
,p_filter_lov_type=>'NONE'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750278020113752)
,p_name=>'FARBCODE_HEX'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'FARBCODE_HEX'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Farbe'
,p_heading_alignment=>'LEFT'
,p_display_sequence=>110
,p_value_alignment=>'LEFT'
,p_attribute_05=>'BOTH'
,p_is_required=>false
,p_max_length=>50
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_imp_page.create_region_column(
 p_id=>wwv_flow_imp.id(115750174929113751)
,p_name=>'VORGABE_CODE_ID'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'VORGABE_CODE_ID'
,p_data_type=>'VARCHAR2'
,p_session_state_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>120
,p_attribute_01=>'Y'
,p_use_as_row_header=>false
,p_enable_sort_group=>false
,p_is_primary_key=>true
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_imp_page.create_interactive_grid(
 p_id=>wwv_flow_imp.id(169527877439812755)
,p_internal_uid=>432795880496793749
,p_is_editable=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SET'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_toolbar_buttons=>'ACTIONS_MENU:SAVE'
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>false
,p_download_formats=>null
,p_enable_mail_download=>true
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_imp_page.create_ig_report(
 p_id=>wwv_flow_imp.id(172579456617381240)
,p_interactive_grid_id=>wwv_flow_imp.id(169527877439812755)
,p_static_id=>'1391759'
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_imp_page.create_ig_report_view(
 p_id=>wwv_flow_imp.id(172579606828381241)
,p_report_id=>wwv_flow_imp.id(172579456617381240)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112388688059155269)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>1
,p_column_id=>wwv_flow_imp.id(115751075877113760)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>116.917
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112387731941155275)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>2
,p_column_id=>wwv_flow_imp.id(115750981837113759)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>65.312
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112385922844155279)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>3
,p_column_id=>wwv_flow_imp.id(115750797280113757)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>317.917
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112385014977155281)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>4
,p_column_id=>wwv_flow_imp.id(115750607554113756)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112384176495155284)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>5
,p_column_id=>wwv_flow_imp.id(115750542292113755)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>74.9167
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112383269683155286)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>6
,p_column_id=>wwv_flow_imp.id(115750455241113754)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>65.9792
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112382355676155288)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>7
,p_column_id=>wwv_flow_imp.id(115750398886113753)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112381477207155290)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>8
,p_column_id=>wwv_flow_imp.id(115750278020113752)
,p_is_visible=>false
,p_is_frozen=>false
);
wwv_flow_imp_page.create_ig_report_column(
 p_id=>wwv_flow_imp.id(112380517478155292)
,p_view_id=>wwv_flow_imp.id(172579606828381241)
,p_display_seq=>9
,p_column_id=>wwv_flow_imp.id(115750174929113751)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(112396211347113072)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(169527506211812751)
,p_button_name=>'CANCEL'
,p_button_action=>'SUBMIT'
,p_button_template_options=>'#DEFAULT#:t-Button--iconLeft'
,p_button_template_id=>wwv_flow_imp.id(98792645238580445)
,p_button_image_alt=>'Abbrechen'
,p_button_position=>'CLOSE'
,p_icon_css_classes=>'fa-times'
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(112390899130113112)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_process_type=>'NATIVE_CLOSE_WINDOW'
,p_process_name=>'CloseDialog'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>21644815412180180
);
wwv_flow_imp_page.create_page_process(
 p_id=>wwv_flow_imp.id(112390456631113112)
,p_process_sequence=>10
,p_process_point=>'BEFORE_HEADER'
,p_process_type=>'NATIVE_PLSQL'
,p_process_name=>'initDatum'
,p_process_sql_clob=>':P51_DATUM_DATE := trunc(to_date(:P51_DATUM, ''DD.MM.YYYY''));'
,p_process_clob_language=>'PLSQL'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
,p_internal_uid=>21645257911180180
);
wwv_flow_imp.component_end;
end;
/
