insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Piotr','Moskowicz','123354426','1','PMO','12','Y','test@test.com','JmqZGQJQBReJTVjaxqSpIUiZJghhSMuy???}?=?<','JmqZGQJQBReJTVjaxqSpIUiZJghhSMuy','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Pawel','Szewel',null,'1','PSZ_ADM',null,'Y',null,'IvXTQQBcOFlPWKHKMznPgssjLjHWfmDt*(?*?n?R^?','IvXTQQBcOFlPWKHKMznPgssjLjHWfmDt','ADM','DE-BE');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Andrzej','Pokora-Motyl',null,'1','APK_ADM',null,'Y',null,'AFUhrETjgoiBxUWHszarnHFXmpvktfbd????L??','AFUhrETjgoiBxUWHszarnHFXmpvktfbd','ADM','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Magdalena','P?onka','01234567','1','MPL','11','Y','test@test.com','BhOsnIGQADEhrzENYmFaMQVSTYHZcEOC??yo?&}?','BhOsnIGQADEhrzENYmFaMQVSTYHZcEOC','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('?ukasz','Szczurek','12345678','1','LSZ','3','Y','test6@test.com','ysCGdpqyuXXzTmnhTnIfcQQUFVRPMUTz\Q{f??t?n?','ysCGdpqyuXXzTmnhTnIfcQQUFVRPMUTz','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Jan','Ugalde-Oporta',null,'1','JUO',null,'Y',null,'IgYPbFnfJVZwsxhtancJOvGhYcDbfjJg?K?yf?S_','IgYPbFnfJVZwsxhtancJOvGhYcDbfjJg','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Pawe?','Szewel',null,'1','PSZ','5','Y','test@test.com','wHoUouLTKdafDIAmLPEFUfXEOTWqKJxq?}3?H?','wHoUouLTKdafDIAmLPEFUfXEOTWqKJxq','MA','DE-BE');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Mateusz','Kopa?ski',null,'1','MKO','6','N','test@test.com','eLUIhyBdQiKgZQGQlVVhAqEKbLLzEJJo??N?p???6','eLUIhyBdQiKgZQGQlVVhAqEKbLLzEJJo','EXT','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Paulina','M?ynik',null,'1','PAM','7','N','test@test.com','puokHBPbyPluwdVzpsYLzBBFXfHlILSF?Z???]?R','puokHBPbyPluwdVzpsYLzBBFXfHlILSF','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Ma?gorzata','Czepiel',null,'1','MCZ','8','Y','test@test.com','dzQhSVsjlHbwTZKQDjKELLuMavWQMhhb?????b?','dzQhSVsjlHbwTZKQDjKELLuMavWQMhhb','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Aleksandra','Cio?',null,'1','ACS','9','Y','test@test.com','OCbOyOjazzHTbLWaPSqTWMREunxfDaLz?%[l?3???','OCbOyOjazzHTbLWaPSqTWMREunxfDaLz','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Michael','Kopp',null,'1','MKP','2','Y','test2@test.com','JCKSntrCjSXmWRmqOMjiuzgJpYtCouaI????:Sc_?','JCKSntrCjSXmWRmqOMjiuzgJpYtCouaI','MA','DE-BY');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('?ukasz','Mazur','123456876','1','LMA','1','Y','test1@test.com','CSmOFOcykNFseEuJAgOxZrIzbEUboRLlr??:^PM??"','CSmOFOcykNFseEuJAgOxZrIzbEUboRLl','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Aleksandra','Ciecha?ska',null,'1','ALC','4','N','test@test.com','kJAbfPozaobYDbSpFIzOmiIeXGqtgnkV??W2???','kJAbfPozaobYDbSpFIzOmiIeXGqtgnkV','EXT','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Tomasz','Rak',null,'1','TRA',null,'Y',null,'kRHUpBjJmmGCVjQqnBIOkVWgIcqGowLtH?????r','kRHUpBjJmmGCVjQqnBIOkVWgIcqGowLt','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Marek','Cienkiewicz',null,'10','MCI_ADM',null,'Y',null,'JYjivjzfHsAmxelGJJZhmHmswWzIuzXY?Vc2?!??','JYjivjzfHsAmxelGJJZhmHmswWzIuzXY','ADM',null);
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Sebastian','Mierisch','12344432156','10','SEM',null,'Y','test@test5.com','LseoOJfFYdzNuyJdcNJwIoygluaLBrlz?????	%','LseoOJfFYdzNuyJdcNJwIoygluaLBrlz','ADM',null);
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Thimo','Fußbroich','1233456','10','THF',null,'Y',null,'uwjXKaQaxWrEJxKkbgTgHAcowpWXIcYQ?~?{?od?','uwjXKaQaxWrEJxKkbgTgHAcowpWXIcYQ','ADM',null);
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Andrzej','Pokora-Motyl',null,'1','APK','0','Y',null,'sziBlCUXsLJcuVmXwHsaRBWszprxtuaWa?0??_?','sziBlCUXsLJcuVmXwHsaRBWszprxtuaW','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Rafa?','Bartnikowski',null,'1','RBA','13','Y',null,'rhMmHJkjkFDyQFGYrJAXvpprpZyexvtj??m???{Zx','rhMmHJkjkFDyQFGYrJAXvpprpZyexvtj','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Bartosz','Stefaniak',null,'1','BST','14','Y',null,'kucnNwguaAkqYoMfMPYYluTcuAButNOC?>%????v','kucnNwguaAkqYoMfMPYYluTcuAButNOC','MA','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Aleksandra','Cio?',null,'1','ACS_ADM',null,'Y',null,'PBiASZQxhSUdkCXYwOZTBOtwPFZmDVzq??X?F;D??','PBiASZQxhSUdkCXYwOZTBOtwPFZmDVzq','ADM','PL');
insert into mitarbeiter (vorname,nachname,handynummer,service_team_id,mitarbeiter_id,reihenfolge,aktiv,email_adresse,password_hash,salt,rolle_id,land_id) values ('Marek','Cienkiewicz',null,'10','MCI',null,'N',null,'AgNmLzGHXXROabkZMYwARXzqWRjfxFLF??8hYY:????','AgNmLzGHXXROabkZMYwARXzqWRjfxFLF','MA','PL');